/**
 * F1 Season Simulator - 2026 Data Foundation
 * Teams, Drivers, and Races based on confirmed 2026 lineups and calendar
 */

// =============================================================================
// TEAMS (11 teams)
// McLaren as strongest per 2025 form and 2026 projections
// =============================================================================

export const TEAMS = [
  {
    id: "mclaren",
    name: "McLaren",
    color: "#FF8000",
    basePace: 90,
    reliability: 91,
    upgradeSchedule: "mid",
    upgradePotential: 9,
    powerUnit: "Mercedes",
  },
  {
    id: "mercedes",
    name: "Mercedes",
    color: "#00D2BE",
    basePace: 95,
    reliability: 92,
    upgradeSchedule: "mid",
    upgradePotential: 6,
    powerUnit: "Mercedes",
  },
  {
    id: "red_bull",
    name: "Red Bull Racing",
    color: "#0600EF",
    basePace: 89,
    reliability: 84,
    upgradeSchedule: "early",
    upgradePotential: 7,
    powerUnit: "Red Bull Ford",
  },
  {
    id: "ferrari",
    name: "Ferrari",
    color: "#DC0000",
    basePace: 93,
    reliability: 88,
    upgradeSchedule: "early",
    upgradePotential: 8,
    powerUnit: "Ferrari",
  },
  {
    id: "williams",
    name: "Williams",
    color: "#005AFF",
    basePace: 76,
    reliability: 86,
    upgradeSchedule: "late",
    upgradePotential: 5,
    powerUnit: "Mercedes",
  },
  {
    id: "racing_bulls",
    name: "Racing Bulls",
    color: "#2B4562",
    basePace: 78,
    reliability: 87,
    upgradeSchedule: "mid",
    upgradePotential: 5,
    powerUnit: "Red Bull Ford",
  },
  {
    id: "aston_martin",
    name: "Aston Martin",
    color: "#006F62",
    basePace: 71,
    reliability: 75,
    upgradeSchedule: "late",
    upgradePotential: 8,
    powerUnit: "Honda",
  },
  {
    id: "haas",
    name: "Haas F1 Team",
    color: "#FFFFFF",
    basePace: 77,
    reliability: 83,
    upgradeSchedule: "none",
    upgradePotential: 3,
    powerUnit: "Ferrari",
  },
  {
    id: "audi",
    name: "Audi",
    color: "#C41E3A",
    basePace: 73,
    reliability: 74,
    upgradeSchedule: "late",
    upgradePotential: 6,
    powerUnit: "Audi",
  },
  {
    id: "alpine",
    name: "Alpine",
    color: "#0090FF",
    basePace: 74,
    reliability: 80,
    upgradeSchedule: "mid",
    upgradePotential: 5,
    powerUnit: "Alpine",
  },
  {
    id: "cadillac",
    name: "Cadillac",
    color: "#0033A0",
    basePace: 68,
    reliability: 72,
    upgradeSchedule: "none",
    upgradePotential: 3,
    powerUnit: "Ferrari",
  },
];

// =============================================================================
// DRIVERS (22 drivers)
// Ratings reflect 2025/2026 form and reputations
// =============================================================================

export const DRIVERS = [
  // McLaren
  {
    id: "norris",
    name: "Lando Norris",
    short: "NOR",
    number: 1,
    teamId: "mclaren",
    flag: "🇬🇧",
    pace: 94,
    consistency: 92,
    wetWeather: 88,
    tyreManagement: 93,
    overtaking: 91,
    defending: 89,
    age: 26,
    contractExpiry: 2,
    reputation: 95,
    form: 95,
    status: "active",
    peakAge: 29,
  },
  {
    id: "piastri",
    name: "Oscar Piastri",
    short: "PIA",
    number: 81,
    teamId: "mclaren",
    flag: "🇦🇺",
    pace: 91,
    consistency: 90,
    wetWeather: 85,
    tyreManagement: 90,
    overtaking: 88,
    defending: 87,
    age: 25,
    contractExpiry: 2,
    reputation: 88,
    form: 88,
    status: "active",
    peakAge: 29,
  },
  // Mercedes
  {
    id: "russell",
    name: "George Russell",
    short: "RUS",
    number: 63,
    teamId: "mercedes",
    flag: "🇬🇧",
    pace: 90,
    consistency: 86,
    wetWeather: 87,
    tyreManagement: 88,
    overtaking: 89,
    defending: 88,
    age: 28,
    contractExpiry: 1,
    reputation: 87,
    form: 87,
    status: "active",
    peakAge: 29,
  },
  {
    id: "antonelli",
    name: "Kimi Antonelli",
    short: "ANT",
    number: 12,
    teamId: "mercedes",
    flag: "🇮🇹",
    pace: 88,
    consistency: 82,
    wetWeather: 84,
    tyreManagement: 85,
    overtaking: 87,
    defending: 86,
    age: 19,
    contractExpiry: 2,
    reputation: 78,
    form: 78,
    status: "active",
    peakAge: 27,
  },
  // Red Bull
  {
    id: "verstappen",
    name: "Max Verstappen",
    short: "VER",
    number: 3,
    teamId: "red_bull",
    flag: "🇳🇱",
    pace: 96,
    consistency: 91,
    wetWeather: 95,
    tyreManagement: 95,
    overtaking: 95,
    defending: 97,
    age: 28,
    contractExpiry: 3,
    reputation: 98,
    form: 98,
    status: "active",
    peakAge: 29,
  },
  {
    id: "hadjar",
    name: "Isack Hadjar",
    short: "HAD",
    number: 6,
    teamId: "red_bull",
    flag: "🇫🇷",
    pace: 82,
    consistency: 78,
    wetWeather: 80,
    tyreManagement: 79,
    overtaking: 81,
    defending: 77,
    age: 21,
    contractExpiry: 2,
    reputation: 74,
    form: 74,
    status: "active",
    peakAge: 27,
  },
  // Ferrari
  {
    id: "leclerc",
    name: "Charles Leclerc",
    short: "LEC",
    number: 16,
    teamId: "ferrari",
    flag: "🇲🇨",
    pace: 93,
    consistency: 85,
    wetWeather: 86,
    tyreManagement: 87,
    overtaking: 90,
    defending: 88,
    age: 28,
    contractExpiry: 3,
    reputation: 93,
    form: 93,
    status: "active",
    peakAge: 30,
  },
  {
    id: "hamilton",
    name: "Lewis Hamilton",
    short: "HAM",
    number: 44,
    teamId: "ferrari",
    flag: "🇬🇧",
    pace: 91,
    consistency: 96,
    wetWeather: 90,
    tyreManagement: 91,
    overtaking: 90,
    defending: 91,
    age: 41,
    contractExpiry: 1,
    reputation: 97,
    form: 97,
    status: "active",
    peakAge: 32,
  },
  // Williams
  {
    id: "albon",
    name: "Alexander Albon",
    short: "ALB",
    number: 23,
    teamId: "williams",
    flag: "🇹🇭",
    pace: 85,
    consistency: 88,
    wetWeather: 84,
    tyreManagement: 86,
    overtaking: 84,
    defending: 87,
    age: 28,
    contractExpiry: 1,
    reputation: 78,
    form: 78,
    status: "active",
    peakAge: 29,
  },
  {
    id: "sainz",
    name: "Carlos Sainz",
    short: "SAI",
    number: 55,
    teamId: "williams",
    flag: "🇪🇸",
    pace: 87,
    consistency: 89,
    wetWeather: 85,
    tyreManagement: 88,
    overtaking: 86,
    defending: 88,
    age: 31,
    contractExpiry: 1,
    reputation: 85,
    form: 85,
    status: "active",
    peakAge: 30,
  },
  // Racing Bulls
  {
    id: "lawson",
    name: "Liam Lawson",
    short: "LAW",
    number: 30,
    teamId: "racing_bulls",
    flag: "🇳🇿",
    pace: 82,
    consistency: 84,
    wetWeather: 82,
    tyreManagement: 83,
    overtaking: 82,
    defending: 81,
    age: 23,
    contractExpiry: 1,
    reputation: 75,
    form: 75,
    status: "active",
    peakAge: 27,
  },
  {
    id: "lindblad",
    name: "Arvid Lindblad",
    short: "LIN",
    number: 41,
    teamId: "racing_bulls",
    flag: "🇬🇧",
    pace: 78,
    consistency: 72,
    wetWeather: 75,
    tyreManagement: 74,
    overtaking: 76,
    defending: 73,
    age: 18,
    contractExpiry: 2,
    reputation: 68,
    form: 68,
    status: "active",
    peakAge: 25,
  },
  // Aston Martin
  {
    id: "alonso",
    name: "Fernando Alonso",
    short: "ALO",
    number: 14,
    teamId: "aston_martin",
    flag: "🇪🇸",
    pace: 88,
    consistency: 91,
    wetWeather: 97,
    tyreManagement: 90,
    overtaking: 87,
    defending: 92,
    age: 44,
    contractExpiry: 1,
    reputation: 94,
    form: 94,
    status: "active",
    peakAge: 32,
  },
  {
    id: "stroll",
    name: "Lance Stroll",
    short: "STR",
    number: 18,
    teamId: "aston_martin",
    flag: "🇨🇦",
    pace: 78,
    consistency: 72,
    wetWeather: 80,
    tyreManagement: 76,
    overtaking: 77,
    defending: 75,
    age: 27,
    contractExpiry: 2,
    reputation: 62,
    form: 62,
    status: "active",
    peakAge: 28,
  },
  // Haas
  {
    id: "ocon",
    name: "Esteban Ocon",
    short: "OCO",
    number: 31,
    teamId: "haas",
    flag: "🇫🇷",
    pace: 82,
    consistency: 85,
    wetWeather: 83,
    tyreManagement: 84,
    overtaking: 82,
    defending: 84,
    age: 29,
    contractExpiry: 1,
    reputation: 73,
    form: 73,
    status: "active",
    peakAge: 29,
  },
  {
    id: "bearman",
    name: "Oliver Bearman",
    short: "BEA",
    number: 87,
    teamId: "haas",
    flag: "🇬🇧",
    pace: 84,
    consistency: 82,
    wetWeather: 83,
    tyreManagement: 83,
    overtaking: 85,
    defending: 82,
    age: 20,
    contractExpiry: 2,
    reputation: 74,
    form: 74,
    status: "active",
    peakAge: 27,
  },
  // Audi
  {
    id: "hulkenberg",
    name: "Nico Hulkenberg",
    short: "HUL",
    number: 27,
    teamId: "audi",
    flag: "🇩🇪",
    pace: 84,
    consistency: 86,
    wetWeather: 85,
    tyreManagement: 85,
    overtaking: 83,
    defending: 85,
    age: 37,
    contractExpiry: 1,
    reputation: 76,
    form: 76,
    status: "active",
    peakAge: 30,
  },
  {
    id: "bortoleto",
    name: "Gabriel Bortoleto",
    short: "BOR",
    number: 5,
    teamId: "audi",
    flag: "🇧🇷",
    pace: 80,
    consistency: 78,
    wetWeather: 79,
    tyreManagement: 80,
    overtaking: 81,
    defending: 78,
    age: 20,
    contractExpiry: 2,
    reputation: 72,
    form: 72,
    status: "active",
    peakAge: 26,
  },
  // Alpine
  {
    id: "gasly",
    name: "Pierre Gasly",
    short: "GAS",
    number: 10,
    teamId: "alpine",
    flag: "🇫🇷",
    pace: 83,
    consistency: 84,
    wetWeather: 84,
    tyreManagement: 83,
    overtaking: 82,
    defending: 83,
    age: 29,
    contractExpiry: 2,
    reputation: 77,
    form: 77,
    status: "active",
    peakAge: 29,
  },
  {
    id: "colapinto",
    name: "Franco Colapinto",
    short: "COL",
    number: 43,
    teamId: "alpine",
    flag: "🇦🇷",
    pace: 79,
    consistency: 76,
    wetWeather: 78,
    tyreManagement: 77,
    overtaking: 79,
    defending: 76,
    age: 22,
    contractExpiry: 1,
    reputation: 70,
    form: 70,
    status: "active",
    peakAge: 27,
  },
  // Cadillac
  {
    id: "perez",
    name: "Sergio Perez",
    short: "PER",
    number: 11,
    teamId: "cadillac",
    flag: "🇲🇽",
    pace: 82,
    consistency: 80,
    wetWeather: 85,
    tyreManagement: 84,
    overtaking: 83,
    defending: 81,
    age: 36,
    contractExpiry: 1,
    reputation: 74,
    form: 74,
    status: "active",
    peakAge: 30,
  },
  {
    id: "bottas",
    name: "Valtteri Bottas",
    short: "BOT",
    number: 77,
    teamId: "cadillac",
    flag: "🇫🇮",
    pace: 83,
    consistency: 85,
    wetWeather: 82,
    tyreManagement: 84,
    overtaking: 81,
    defending: 83,
    age: 36,
    contractExpiry: 1,
    reputation: 72,
    form: 72,
    status: "active",
    peakAge: 30,
  },
];

// =============================================================================
// RACES (24 races - 2026 calendar)
// =============================================================================

export const RACES = [
  {
    round: 1,
    name: "Australian Grand Prix",
    location: "Melbourne",
    country: "Australia",
    flag: "🇦🇺",
    date: "2026-03-08",
    circuitType: "street",
    overtakingDifficulty: 6,
    weatherProbability: { dry: 75, mixed: 20, wet: 5 },
    isSprint: false,
    isNew: false,
  },
  {
    round: 2,
    name: "Chinese Grand Prix",
    location: "Shanghai",
    country: "China",
    flag: "🇨🇳",
    date: "2026-03-15",
    circuitType: "balanced",
    overtakingDifficulty: 5,
    weatherProbability: { dry: 70, mixed: 25, wet: 5 },
    isSprint: true,
    isNew: false,
  },
  {
    round: 3,
    name: "Japanese Grand Prix",
    location: "Suzuka",
    country: "Japan",
    flag: "🇯🇵",
    date: "2026-03-29",
    circuitType: "downforce",
    overtakingDifficulty: 4,
    weatherProbability: { dry: 65, mixed: 25, wet: 10 },
    isSprint: false,
    isNew: false,
  },
  {
    round: 4,
    name: "Bahrain Grand Prix",
    location: "Sakhir",
    country: "Bahrain",
    flag: "🇧🇭",
    date: "2026-04-12",
    circuitType: "power",
    overtakingDifficulty: 4,
    weatherProbability: { dry: 95, mixed: 4, wet: 1 },
    isSprint: false,
    isNew: false,
  },
  {
    round: 5,
    name: "Saudi Arabian Grand Prix",
    location: "Jeddah",
    country: "Saudi Arabia",
    flag: "🇸🇦",
    date: "2026-04-19",
    circuitType: "street",
    overtakingDifficulty: 3,
    weatherProbability: { dry: 98, mixed: 1, wet: 1 },
    isSprint: false,
    isNew: false,
  },
  {
    round: 6,
    name: "Miami Grand Prix",
    location: "Miami",
    country: "USA",
    flag: "🇺🇸",
    date: "2026-05-03",
    circuitType: "street",
    overtakingDifficulty: 6,
    weatherProbability: { dry: 80, mixed: 15, wet: 5 },
    isSprint: true,
    isNew: false,
  },
  {
    round: 7,
    name: "Canadian Grand Prix",
    location: "Montreal",
    country: "Canada",
    flag: "🇨🇦",
    date: "2026-05-24",
    circuitType: "street",
    overtakingDifficulty: 4,
    weatherProbability: { dry: 60, mixed: 30, wet: 10 },
    isSprint: true,
    isNew: false,
  },
  {
    round: 8,
    name: "Monaco Grand Prix",
    location: "Monaco",
    country: "Monaco",
    flag: "🇲🇨",
    date: "2026-06-07",
    circuitType: "street",
    overtakingDifficulty: 10,
    weatherProbability: { dry: 70, mixed: 20, wet: 10 },
    isSprint: false,
    isNew: false,
  },
  {
    round: 9,
    name: "Spanish Grand Prix",
    location: "Barcelona-Catalunya",
    country: "Spain",
    flag: "🇪🇸",
    date: "2026-06-14",
    circuitType: "downforce",
    overtakingDifficulty: 6,
    weatherProbability: { dry: 85, mixed: 12, wet: 3 },
    isSprint: false,
    isNew: false,
  },
  {
    round: 10,
    name: "Austrian Grand Prix",
    location: "Spielberg",
    country: "Austria",
    flag: "🇦🇹",
    date: "2026-06-28",
    circuitType: "power",
    overtakingDifficulty: 3,
    weatherProbability: { dry: 65, mixed: 25, wet: 10 },
    isSprint: false,
    isNew: false,
  },
  {
    round: 11,
    name: "British Grand Prix",
    location: "Silverstone",
    country: "Great Britain",
    flag: "🇬🇧",
    date: "2026-07-05",
    circuitType: "power",
    overtakingDifficulty: 3,
    weatherProbability: { dry: 55, mixed: 30, wet: 15 },
    isSprint: true,
    isNew: false,
  },
  {
    round: 12,
    name: "Belgian Grand Prix",
    location: "Spa-Francorchamps",
    country: "Belgium",
    flag: "🇧🇪",
    date: "2026-07-19",
    circuitType: "power",
    overtakingDifficulty: 2,
    weatherProbability: { dry: 50, mixed: 35, wet: 15 },
    isSprint: false,
    isNew: false,
  },
  {
    round: 13,
    name: "Hungarian Grand Prix",
    location: "Budapest",
    country: "Hungary",
    flag: "🇭🇺",
    date: "2026-07-26",
    circuitType: "downforce",
    overtakingDifficulty: 7,
    weatherProbability: { dry: 75, mixed: 20, wet: 5 },
    isSprint: false,
    isNew: false,
  },
  {
    round: 14,
    name: "Dutch Grand Prix",
    location: "Zandvoort",
    country: "Netherlands",
    flag: "🇳🇱",
    date: "2026-08-23",
    circuitType: "downforce",
    overtakingDifficulty: 8,
    weatherProbability: { dry: 60, mixed: 30, wet: 10 },
    isSprint: true,
    isNew: false,
  },
  {
    round: 15,
    name: "Italian Grand Prix",
    location: "Monza",
    country: "Italy",
    flag: "🇮🇹",
    date: "2026-09-06",
    circuitType: "power",
    overtakingDifficulty: 3,
    weatherProbability: { dry: 80, mixed: 15, wet: 5 },
    isSprint: false,
    isNew: false,
  },
  {
    round: 16,
    name: "Madrid Grand Prix",
    location: "Madrid",
    country: "Spain",
    flag: "🇪🇸",
    date: "2026-09-13",
    circuitType: "street",
    overtakingDifficulty: 5,
    weatherProbability: { dry: 85, mixed: 12, wet: 3 },
    isSprint: false,
    isNew: true,
  },
  {
    round: 17,
    name: "Azerbaijan Grand Prix",
    location: "Baku",
    country: "Azerbaijan",
    flag: "🇦🇿",
    date: "2026-09-26",
    circuitType: "street",
    overtakingDifficulty: 4,
    weatherProbability: { dry: 90, mixed: 8, wet: 2 },
    isSprint: false,
    isNew: false,
  },
  {
    round: 18,
    name: "Singapore Grand Prix",
    location: "Singapore",
    country: "Singapore",
    flag: "🇸🇬",
    date: "2026-10-11",
    circuitType: "street",
    overtakingDifficulty: 9,
    weatherProbability: { dry: 50, mixed: 35, wet: 15 },
    isSprint: true,
    isNew: false,
  },
  {
    round: 19,
    name: "United States Grand Prix",
    location: "Austin",
    country: "USA",
    flag: "🇺🇸",
    date: "2026-10-25",
    circuitType: "balanced",
    overtakingDifficulty: 4,
    weatherProbability: { dry: 85, mixed: 12, wet: 3 },
    isSprint: false,
    isNew: false,
  },
  {
    round: 20,
    name: "Mexican Grand Prix",
    location: "Mexico City",
    country: "Mexico",
    flag: "🇲🇽",
    date: "2026-11-01",
    circuitType: "power",
    overtakingDifficulty: 4,
    weatherProbability: { dry: 90, mixed: 8, wet: 2 },
    isSprint: false,
    isNew: false,
  },
  {
    round: 21,
    name: "Brazilian Grand Prix",
    location: "São Paulo",
    country: "Brazil",
    flag: "🇧🇷",
    date: "2026-11-08",
    circuitType: "balanced",
    overtakingDifficulty: 3,
    weatherProbability: { dry: 60, mixed: 30, wet: 10 },
    isSprint: false,
    isNew: false,
  },
  {
    round: 22,
    name: "Las Vegas Grand Prix",
    location: "Las Vegas",
    country: "USA",
    flag: "🇺🇸",
    date: "2026-11-21",
    circuitType: "street",
    overtakingDifficulty: 5,
    weatherProbability: { dry: 95, mixed: 4, wet: 1 },
    isSprint: false,
    isNew: false,
  },
  {
    round: 23,
    name: "Qatar Grand Prix",
    location: "Lusail",
    country: "Qatar",
    flag: "🇶🇦",
    date: "2026-11-29",
    circuitType: "power",
    overtakingDifficulty: 4,
    weatherProbability: { dry: 98, mixed: 1, wet: 1 },
    isSprint: false,
    isNew: false,
  },
  {
    round: 24,
    name: "Abu Dhabi Grand Prix",
    location: "Yas Marina",
    country: "Abu Dhabi",
    flag: "🇦🇪",
    date: "2026-12-06",
    circuitType: "balanced",
    overtakingDifficulty: 5,
    weatherProbability: { dry: 98, mixed: 1, wet: 1 },
    isSprint: false,
    isNew: false,
  },
];

// =============================================================================
// RESERVE DRIVERS (~12 drivers, status: 'reserve')
// =============================================================================

export const RESERVE_DRIVERS = [
  {
    id: "schumacher_m",
    name: "Mick Schumacher",
    short: "MSC",
    number: null,
    teamId: null,
    flag: "🇩🇪",
    pace: 72,
    consistency: 70,
    wetWeather: 68,
    tyreManagement: 70,
    overtaking: 70,
    defending: 68,
    age: 27,
    contractExpiry: 0,
    reputation: 68,
    form: 68,
    status: "reserve",
    peakAge: 28,
  },
  {
    id: "de_vries",
    name: "Nyck de Vries",
    short: "DEV",
    number: null,
    teamId: null,
    flag: "🇳🇱",
    pace: 68,
    consistency: 70,
    wetWeather: 65,
    tyreManagement: 68,
    overtaking: 66,
    defending: 64,
    age: 31,
    contractExpiry: 0,
    reputation: 62,
    form: 62,
    status: "reserve",
    peakAge: 28,
  },
  {
    id: "oward",
    name: "Patricio O'Ward",
    short: "OWA",
    number: null,
    teamId: null,
    flag: "🇲🇽",
    pace: 76,
    consistency: 72,
    wetWeather: 70,
    tyreManagement: 74,
    overtaking: 78,
    defending: 70,
    age: 27,
    contractExpiry: 0,
    reputation: 71,
    form: 71,
    status: "reserve",
    peakAge: 28,
  },
  {
    id: "doohan",
    name: "Jack Doohan",
    short: "DOO",
    number: null,
    teamId: null,
    flag: "🇦🇺",
    pace: 72,
    consistency: 68,
    wetWeather: 70,
    tyreManagement: 70,
    overtaking: 72,
    defending: 66,
    age: 24,
    contractExpiry: 0,
    reputation: 66,
    form: 66,
    status: "reserve",
    peakAge: 26,
  },
  {
    id: "crawford",
    name: "Jak Crawford",
    short: "CRA",
    number: null,
    teamId: null,
    flag: "🇺🇸",
    pace: 76,
    consistency: 70,
    wetWeather: 72,
    tyreManagement: 74,
    overtaking: 74,
    defending: 70,
    age: 22,
    contractExpiry: 0,
    reputation: 72,
    form: 72,
    status: "reserve",
    peakAge: 26,
  },
  {
    id: "maloney",
    name: "Zane Maloney",
    short: "MAL",
    number: null,
    teamId: null,
    flag: "🇧🇧",
    pace: 72,
    consistency: 68,
    wetWeather: 68,
    tyreManagement: 70,
    overtaking: 72,
    defending: 64,
    age: 23,
    contractExpiry: 0,
    reputation: 65,
    form: 65,
    status: "reserve",
    peakAge: 26,
  },
  {
    id: "maini",
    name: "Kush Maini",
    short: "MAI",
    number: null,
    teamId: null,
    flag: "🇮🇳",
    pace: 68,
    consistency: 66,
    wetWeather: 64,
    tyreManagement: 68,
    overtaking: 66,
    defending: 62,
    age: 26,
    contractExpiry: 0,
    reputation: 60,
    form: 60,
    status: "reserve",
    peakAge: 27,
  },
  {
    id: "aron",
    name: "Paul Aron",
    short: "ARO",
    number: null,
    teamId: null,
    flag: "🇪🇪",
    pace: 70,
    consistency: 68,
    wetWeather: 66,
    tyreManagement: 68,
    overtaking: 68,
    defending: 64,
    age: 22,
    contractExpiry: 0,
    reputation: 63,
    form: 63,
    status: "reserve",
    peakAge: 26,
  },
  {
    id: "ilott",
    name: "Callum Ilott",
    short: "ILO",
    number: null,
    teamId: null,
    flag: "🇬🇧",
    pace: 72,
    consistency: 72,
    wetWeather: 68,
    tyreManagement: 72,
    overtaking: 70,
    defending: 68,
    age: 27,
    contractExpiry: 0,
    reputation: 64,
    form: 64,
    status: "reserve",
    peakAge: 27,
  },
  {
    id: "grey",
    name: "Oliver Grey",
    short: "GRE",
    number: null,
    teamId: null,
    flag: "🇬🇧",
    pace: 64,
    consistency: 60,
    wetWeather: 58,
    tyreManagement: 62,
    overtaking: 62,
    defending: 58,
    age: 19,
    contractExpiry: 0,
    reputation: 58,
    form: 58,
    status: "reserve",
    peakAge: 25,
  },
  {
    id: "mini",
    name: "Gabriele Mini",
    short: "MIN",
    number: null,
    teamId: null,
    flag: "🇮🇹",
    pace: 68,
    consistency: 64,
    wetWeather: 62,
    tyreManagement: 66,
    overtaking: 66,
    defending: 62,
    age: 20,
    contractExpiry: 0,
    reputation: 61,
    form: 61,
    status: "reserve",
    peakAge: 25,
  },
];

// =============================================================================
// FUTURE ROOKIES (10 generated rookies for seasons 5–10, ages 17–19 in 2026)
// =============================================================================

export const FUTURE_ROOKIES = [
  { id: "rookie_1", name: "Luca Romano", short: "ROM", number: null, teamId: null, flag: "🇮🇹", pace: 60, consistency: 56, wetWeather: 58, tyreManagement: 58, overtaking: 62, defending: 56, age: 18, contractExpiry: 0, reputation: 55, form: 55, status: "junior", peakAge: 26 },
  { id: "rookie_2", name: "Theo van Berg", short: "VAN", number: null, teamId: null, flag: "🇳🇱", pace: 62, consistency: 60, wetWeather: 62, tyreManagement: 61, overtaking: 64, defending: 60, age: 19, contractExpiry: 0, reputation: 62, form: 62, status: "junior", peakAge: 27 },
  { id: "rookie_3", name: "Enzo Davidson", short: "DAV", number: null, teamId: null, flag: "🇫🇷", pace: 59, consistency: 58, wetWeather: 60, tyreManagement: 60, overtaking: 62, defending: 58, age: 17, contractExpiry: 0, reputation: 52, form: 52, status: "junior", peakAge: 26 },
  { id: "rookie_4", name: "Felix Eriksson", short: "ERI", number: null, teamId: null, flag: "🇸🇪", pace: 61, consistency: 60, wetWeather: 60, tyreManagement: 62, overtaking: 62, defending: 60, age: 18, contractExpiry: 0, reputation: 60, form: 60, status: "junior", peakAge: 27 },
  { id: "rookie_5", name: "Yuki Tanaka", short: "TAN", number: null, teamId: null, flag: "🇯🇵", pace: 63, consistency: 61, wetWeather: 63, tyreManagement: 63, overtaking: 64, defending: 62, age: 19, contractExpiry: 0, reputation: 63, form: 63, status: "junior", peakAge: 27 },
  { id: "rookie_6", name: "Oscar Mendes", short: "MEN", number: null, teamId: null, flag: "🇧🇷", pace: 62, consistency: 59, wetWeather: 62, tyreManagement: 61, overtaking: 64, defending: 60, age: 18, contractExpiry: 0, reputation: 58, form: 58, status: "junior", peakAge: 26 },
  { id: "rookie_7", name: "James Morrison", short: "MOR", number: null, teamId: null, flag: "🇬🇧", pace: 62, consistency: 60, wetWeather: 60, tyreManagement: 62, overtaking: 63, defending: 60, age: 19, contractExpiry: 0, reputation: 61, form: 61, status: "junior", peakAge: 28 },
  { id: "rookie_8", name: "Rafael Costa", short: "COS", number: null, teamId: null, flag: "🇪🇸", pace: 58, consistency: 58, wetWeather: 58, tyreManagement: 60, overtaking: 62, defending: 58, age: 17, contractExpiry: 0, reputation: 50, form: 50, status: "junior", peakAge: 26 },
  { id: "rookie_9", name: "Liam O'Brien", short: "OBR", number: null, teamId: null, flag: "🇺🇸", pace: 63, consistency: 61, wetWeather: 62, tyreManagement: 63, overtaking: 64, defending: 61, age: 18, contractExpiry: 0, reputation: 64, form: 64, status: "junior", peakAge: 27 },
  { id: "rookie_10", name: "Aiden Schmidt", short: "SCH", number: null, teamId: null, flag: "🇩🇪", pace: 62, consistency: 62, wetWeather: 61, tyreManagement: 63, overtaking: 63, defending: 62, age: 19, contractExpiry: 0, reputation: 65, form: 65, status: "junior", peakAge: 27 },
];

// =============================================================================
// CONTRACT LENGTHS (suggested contract length by team tier)
// =============================================================================

export const CONTRACT_LENGTHS = {
  /** Top teams: 2–3 years */
  top: { min: 2, max: 3 },
  /** Midfield: 1–2 years */
  midfield: { min: 1, max: 2 },
  /** Lower teams: 1 year */
  lower: { min: 1, max: 1 },
};

// =============================================================================
// TEAM BUDGETS (relative budget tier per team)
// =============================================================================

export const TEAM_BUDGETS = {
  mclaren: 300,
  red_bull: 300,
  mercedes: 300,
  ferrari: 300,
  williams: 180,
  aston_martin: 180,
  alpine: 180,
  racing_bulls: 120,
  haas: 120,
  audi: 120,
  cadillac: 80,
};

// =============================================================================
// SIMULATION MODES (chaos, safety car, transfers, upgrades, firing/retirement)
// =============================================================================

export const SIMULATION_MODES = {
  realistic: {
    chaosLevel: 4,
    safetyCarFrequency: 5,
    transferActivity: 4,
    upgradeVariance: 4,
    firingProbability: 0.25,
    retirementProbability: 0.15,
    rookiePromotionThreshold: 78,
    description: "Grounded in real F1 patterns",
  },
  wildcard: {
    chaosLevel: 8,
    safetyCarFrequency: 8,
    transferActivity: 9,
    upgradeVariance: 8,
    firingProbability: 0.6,
    retirementProbability: 0.35,
    rookiePromotionThreshold: 65,
    description: "Chaos reigns — anything can happen",
  },
};
